import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from mne.io import RawArray
from mne import create_info
from mne.viz import set_browser_backend
from scipy.signal import find_peaks
from pathlib import Path


"""
peak.py — EMG Peak Detection Module
-----------------------------------

This module defines the `EMGPeakAnalyzer` class, which detects peaks in EMG recordings.
It is designed to be used in conjunction with CSV files generated by the `EMGRecorder`
class elsewhere in the project.

Functionality:
--------------
The module:
- Reads a timestamped EMG signal from a CSV file
- Converts units if needed (mV → µV)
- Applies optional filtering (low-pass)
- Detects peaks above a specified amplitude percentile
- Enforces a minimum time between peaks
- Optionally shows plots
- Saves the analysis result as `peaks.txt` next to the CSV

***  Where are the files saved?  ***
--------------------------
When you record EMG using the GUI and the `EMGRecorder`, each session is saved to:

    emg-recordings/YYYY-MM-DD_HH-MM-SS/

Inside that folder, you'll find:
    - `emg.csv`       ← Raw timestamped EMG data (written during recording)
    - `peaks.txt`     ← Peak summary report (written after recording stops)

This structure keeps recordings and their corresponding analysis output together
for easy navigation, sharing, and future automation.

Expected CSV format:
--------------------
The CSV should contain:
- `timestamp` column (seconds)
- One or more EMG channels, named like:
    - `ch1 (µV)`, `ch2 (µV)`, etc. (new format)
    - or `emg` (legacy format in mV — converted internally)
- Optional `event` column with 0/1 flags for manually marked timestamps

"""


class EMGPeakAnalyzer:
    def __init__(self, csv_path, sampling_rate=220, height_percentile=98, min_distance=3):
        """
        Initialize the analyzer with path and parameters.

        Parameters:
        -----------
        csv_path : str or Path
            Path to the EMG CSV file
        sampling_rate : int
            Sampling rate of EMG data (Hz)
        height_percentile : float
            Threshold for peak detection (percentile of signal amplitude)
        min_distance : float
            Minimum time (in seconds) between peaks
        """
        self.csv_path = Path(csv_path)
        self.sampling_rate = sampling_rate
        self.height_percentile = height_percentile
        self.min_distance = min_distance

        self.df_emg = None
        self.raw = None
        self.raw_filtered = None
        self.peaks = None
        self.times = None

    def _load_data(self):
        self.df_emg = pd.read_csv(self.csv_path)

        if 'emg' in self.df_emg.columns:
            emg_signal = self.df_emg['emg'].dropna().values * 1e3
        elif 'ch1 (µV)' in self.df_emg.columns:
            emg_signal = self.df_emg['ch1 (µV)'].dropna().values
        elif any(col.startswith('ch') and '(µV)' in col for col in self.df_emg.columns):
            ch_cols = [col for col in self.df_emg.columns if col.startswith('ch') and '(µV)' in col]
            emg_signal = self.df_emg[ch_cols[0]].dropna().values
        else:
            raise ValueError(f"No EMG column found. Available columns: {self.df_emg.columns.tolist()}")

        self.time_vector = self.df_emg['timestamp'].iloc[:len(emg_signal)].values
        info = create_info(ch_names=['EMG'], sfreq=self.sampling_rate, ch_types=['emg'])
        self.raw = RawArray(emg_signal.reshape(1, -1).astype(np.float64), info)

    def _filter_data(self):
        self.raw_filtered = self.raw.copy()
        self.raw_filtered.filter(None, 100, method="iir", phase="forward", picks="emg")

    def _detect_peaks(self):
        start_idx = 0
        stop_idx = self.raw_filtered.n_times
        data, self.times = self.raw_filtered[:, start_idx:stop_idx]
        data -= data.mean()

        self.peaks = find_peaks(
            data.squeeze(),
            height=np.percentile(data.squeeze(), self.height_percentile),
            distance=self.min_distance * self.sampling_rate
        )[0]

    def _save_results(self):
        output_file = self.csv_path.with_name("peaks.txt")

        # relative paths for display
        relative_csv_path = self.csv_path.relative_to(Path.cwd())
        relative_output_path = output_file.relative_to(Path.cwd())

        with open(output_file, 'w') as f:
            f.write(f"EMG File: {relative_csv_path}\n")
            f.write(f"Output File: {relative_output_path.name}\n")
            f.write(f"Number of peaks: {len(self.peaks)}\n")
            f.write(f"Height percentile: {self.height_percentile}\n")
            f.write(f"Min distance: {self.min_distance} seconds\n")
            f.write(f"Sampling rate: {self.sampling_rate} Hz\n")
            f.write(f"Signal duration: {self.raw.times[-1]:.2f} seconds\n")
        print(f"[PeakAnalyzer] Results saved to: {relative_output_path}")

    def _plot(self):
        fig, ax = plt.subplots(1, 1, layout="constrained")
        ax.plot(self.times, self.raw_filtered.get_data().squeeze() - self.raw_filtered.get_data().mean(), label='Filtered EMG')
        for peak in self.peaks:
            ax.axvline(self.times[peak], color='red', linestyle='--', alpha=0.6)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Amplitude (µV)")
        ax.set_title(f"EMG Signal with {len(self.peaks)} Peaks")
        ax.legend()
        plt.show()

    def run(self, show_plots=False, save_results=True):
        """
        Run the full peak detection pipeline.

        Parameters:
        -----------
        show_plots : bool
            Whether to display the signal + peak plot
        save_results : bool
            Whether to write a summary to peaks.txt

        Returns:
        --------
        dict : results containing metadata and peak info
        """
        print(f"[PeakAnalyzer] Analyzing: {self.csv_path}")
        self._load_data()
        self._filter_data()
        self._detect_peaks()

        if save_results:
            self._save_results()

        if show_plots:
            set_browser_backend("matplotlib")
            self._plot()

        return {
            'csv_file_path': str(self.csv_path),
            'num_peaks': len(self.peaks),
            'peak_times': self.times[self.peaks] if len(self.peaks) > 0 else [],
            'sampling_rate': self.sampling_rate,
            'signal_duration': self.raw.times[-1],
            'raw_data': self.raw,
            'filtered_data': self.raw_filtered
        }
